name: Release
run-name: Building release package
on: 
  push:
    branches:
      - main

jobs:
  fetch-version:
    name: Fetch Next Version
    uses: dcgoodnow/AndroidUnityPackage/.github/workflows/tag-version.yml
    with:
      dryrun: true
  build-android:
    name: Build Android Plugin
    uses: dcgoodnow/AndroidUnityPackage/.github/workflows/build-android.yml
  publish-npm:
    name: Publish package to NPM
    needs: [build-android, fetch-version]
    uses: dcgoodnow/AndroidUnityPackage/.github/workflows/upload-package.yml
    secrets: inherit
    with:
      version: ${{ needs.fetch-version.outputs.tagversion }}
  tag-commit:
    name: Tag new commit
    needs: publish-npm
    uses: dcgoodnow/AndroidUnityPackage/.github/workflows/tag-version.yml
    secrets: inherit
    permissions: 
      contents: write